### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by ZekNikZ** [ZekNikZ/CSI3471-Resume-Builder#11]
Simple requirements

**Comment by nnazo** [comment]
Requirements have been written in the simple format and should be completed now. In case anyone wants to read through them to try to spot anything needing correction, I'll wait a bit to close this issue.

**Comment by ZekNikZ** [comment]
I think they look good, someone else can check them too if they want. I just changed the capitalization of a few words for consistency and added a small clause for clarity (in no. 3).

**Comment by AshleyLuEllen** [comment]
@nnazo @brooklynnStone1 I noticed that in the traceability matrix we go to R 09 and on the list only to R 08

**Comment by nnazo** [comment]
I have added the simple requirement for R09 in the requirements document. I had not seen there was another requirement because I had used the list from the iteration 1 ideas document.
