### ISSUE TITLE
Resume data and subsidiary classes

### ISSUE THREAD

**Issue by ZekNikZ** [ZekNikZ/CSI3471-Resume-Builder#18]
This includes the `Resume` class, as well as `Category` (with its subclasses) and `Item` classes.

**Comment by AshleyLuEllen** [comment]
Thinking about changing Item to Experience. Currently work and education are ExperienceCategory and they are the only thing that use Item. Opinions?

**Comment by ZekNikZ** [comment]
@nnazo @brooklynnStone1 @MicahSchiewe @ZekNikZ see above comment ^

**Comment by ZekNikZ** [comment]
I personally don’t see us adding another category that uses similar Items down the line, so I am okay with this change

**Comment by nnazo** [comment]
This seems like a reasonable change, I don't see a problem with it.

**Comment by brooklynnStone1** [comment]
Sounds like a good change! Thank you Ashley

**Comment by MicahSchiewe** [comment]
Sorry I'm late. Yeah, that seems right Ashley. Especially since Items are the defining trait of the Experience category, so another Category which uses them would in essence be a modified Experience category.

**Comment by nnazo** [comment]
Now that I'm writing the resume file manager, I've encountered that your constructors are all package private and I can't use them. Is there a specific reason?

**Comment by AshleyLuEllen** [comment]
@nnazo Sorry, just fixed. If you find any other function that you might need tell me. Also changed Item to Experience, moved the categories to a separate package, and abstracted some functionality to a ResumeComponent class (id and visibility).
