### ISSUE TITLE
Resume file importer/exporter

### ISSUE THREAD

**Issue by ZekNikZ** [ZekNikZ/CSI3471-Resume-Builder#19]
Any classes/features which are required to convert a resume data JSON file into a `Resume` instance, and vice versa.

**Comment by ZekNikZ** [comment]
From a quick glance, GSON and JSON.simple seem like they might be helpful libraries

**Comment by nnazo** [comment]
I took a look at them and GSON seems more flexible, will probably go with it.

Also, should this be within the `export` package or in its own? I was planning to have one class `ResumeFileManager` or something along those lines that had both the `import` and `export` methods.

**Comment by ZekNikZ** [comment]
Hmmm, good question. Up to you. We could also add a `file` package or something.

**Comment by nnazo** [comment]
Went ahead and created the `file` package. Also worth noting that I won't be able to retrieve `User` metadata for now, but I'll leave comments in my code where applicable.

**Comment by nnazo** [comment]
I have gone ahead and created a branch `data-file` containing classes `Metadata`, `ResumeFile` and `ResumeFileManager`. `Metadata` is mostly a skeleton as of right now because of no access to `User`.

If you spot anything that I missed, please let me know and I'll fix it.

**Comment by nnazo** [comment]
The `data-file` branch has been merged into master, so I"ll close this issue out.
