### ISSUE TITLE
System Sequence Diagrams

### ISSUE THREAD

**Issue by ZekNikZ** [ZekNikZ/CSI3471-Resume-Builder#2]
Complete your assigned System Sequence Diagrams

_Assigned retroactively._

**Comment by ZekNikZ** [comment]
We need to make actors and System both have colons. Also, remove all self-messages.

**Comment by ZekNikZ** [comment]
Also please export as a PDF using the "Diagrams as Image" feature. Make sure to put the diagrams in portrait mode with a frame.

**Comment by ZekNikZ** [comment]
I have finished my updates to the SSDs. I uploaded each one to the Google Drive folder.

**Comment by nnazo** [comment]
SSDs 13, 15, and 16 have all had their necessary corrections made (removing system self calls), and have been exported as requested in the Google Drive folder.

**Comment by AshleyLuEllen** [comment]
I fixed my three SSD's
