### ISSUE TITLE
Users and User Manager Controller

### ISSUE THREAD

**Issue by ZekNikZ** [ZekNikZ/CSI3471-Resume-Builder#21]
User base class and subclasses and controller class for the eventual User Manager GUI.

**Comment by MicahSchiewe** [comment]
Added the first round of this in the branch add-user. Please let me know what I missed so I can go and add that before we merge into Master. (I doubt I was done)(Also, I know the stuff in UserDBC is going to be dummied out until we start adding a database, we'll deal with that when we get there)
