### ISSUE TITLE
Java Doc Comments

### ISSUE THREAD

**Issue by brooklynnStone1** [ZekNikZ/CSI3471-Resume-Builder#40]

**Comment by ZekNikZ** [comment]
**Make sure to:**

1. All classes **must** have Javadoc comments.
2. All protected and public methods and non-obvious (from the name) fields **must** have Javadoc comments.
3. All private and package-private methods and obvious (from the name) fields **should** have Javadoc comments.
4. All method Javadoc comments **must** have **all** parameters (`@param`), returns (`@returns`), and throws (`@throws`). **Make sure to put _BOTH_ the _name_ and _description_ of parameters, returns, and throws!**
5. All **class-level** Javadoc comments **should** have `@author` tags.
6. Always write **custom** Javadoc comments for methods that differ from their base class version (e.g., `toString`).
7. Double-check all copy-and-pasted Javadoc comments.
