### ISSUE TITLE
HeaderCategoryEditPane editing header data

### ISSUE THREAD

**Issue by MicahSchiewe** [ZekNikZ/CSI3471-Resume-Builder#42]
When loading text into a JTextField, it will replace newlines with spaces (e.g., "619 Lane Street\nOak River, TX" becomes "619 Lane Street Oak River, TX"). This means that multi-line addresses get reduced to one line when loaded into the editor in the HeaderCategoryEditPane.

**Comment by brooklynnStone1** [comment]
Thanks Micah, I'll fix that now. It will get pushed to the CategoryEditorModal. Is that ok or do you want it somewhere else?

**Comment by MicahSchiewe** [comment]
You can update it with your Javadocs comments, it would probably just cause a merge conflict otherwise.

**Comment by brooklynnStone1** [comment]
Are you expecting the user to type \n for a newline? Or are you adding that manually

**Comment by brooklynnStone1** [comment]
Actually I see what you're saying. So I need to make it not a field and maybe a text area of some sort so that you can have multiple lines right?

**Comment by MicahSchiewe** [comment]
Yeah, that would work.

**Comment by brooklynnStone1** [comment]
check it out! I tested it with an address and it works well. let me know if it needs more work, otherwise you can close this

**Comment by MicahSchiewe** [comment]
Yeah, that worked. Looks like it wacks out if provided a 3-line address (graphical issue), but that's unimportant since addresses are only ever really denoted with two lines, as far as I'm aware.

We can close this issue as soon as we get that merged into Master.

**Comment by brooklynnStone1** [comment]
Sounds good! Thanks for letting me know that you had that problem!
